### ISSUE TITLE
Element type of samplers

### ISSUE THREAD

**Issue by tjungni** [QEDjl-project/QEDevents.jl#19]
Samplers should be able to generate either coordinates or sets of `SFourMomentum`.
We need to decide if the eltype of a sampler is already determined at construction or if `rand` should be able to be called for both options on a sampler. We also need to define a type for the eltype of samplers that generate momenta because the element type is technically not `SFourMomentum` but an array of `SFourMomentum`.

It could look something like this:
```
rand(rng, sampler, PhaseSpace(Float64)) -> coordinates
rand(rng, sampler, PhaseSpace(SFourMomentum, eltype_of_momenta)) -> momenta
```

**Comment by szabo137** [comment]
With the introduction of phase space points, this is solved.
